version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: deploy/Dockerfile
    environment:
      SERVER_ENDPOINT: "http://server:8080"
    ports:
      - "80:80"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: deploy/Dockerfile
    environment:
      PROFILE: "local"
      MYSQL_HOST: "localhost"
      DB_USERNAME: "user"
      DB_PASSWORD: "password"
      DB_NAME: "library"
    ports:
      - "8080:8080"